### ISSUE TITLE
Version missing from composer.json

### ISSUE THREAD

**Issue by alexoanea** [mention-me/magento2-integration#1]
@chris-pook I know this is not meant to be a marketplace app but I have still ran the M2 validation using the tool provided by Magento https://github.com/magento/marketplace-tools and got the following errors:

1. `ERROR - "magento2-integration-1.0.0.zip": Alternate folder structure is currently not supported`

   Any idea why it's reporting this? I can see the `composer.json` has the autoload->psr-4 defined

2. `ERROR - "magento2-integration-1.0.0.zip": The 'version' field in "composer.json" is missing, empty or not in expected format. The 'version' field is required and needs to be of the following form as described here: https://getcomposer.org/doc/04-schema.md#version .`

   I know that the version is currently specified in the `/app/code/MentionMe/MentionMe/etc/module.xml` file but considering the extension has a `composer.json` file in the root I would expect the version to be specified there as well.

**Comment by chris-pook** [comment]
Hi @alexoanea , thanks. Good call running the marketplace tool. Another good resource for code QA is https://github.com/magento/magento-coding-standard. I use both of these when producing modules.

Regarding the marketplace tool output, both of these errors are expected when testing the repository zip download from GitHub. The marketplace upload process is very strict and enforces some slightly odd conventions which I would always suggest to omit from the code repository.

The "Alternate folder structure is currently not supported" one, like you say is not so much a problem of the module not working (as the PSR-4 definition is correct). I assume Magento do something internally for which this causes issues. Personally I would not include the app/code directory structure in the repository as standard. However, the brief for this module was to lower the bar for on-boarding MentionMe clients, making it as simple as possible to get up and running. The only way to allow a fully drag and drop install for less technically adept merchants using FTP etc is to have the repository zip contain the app/code directory structure.

The "The 'version' field in composer.json is missing" is also contentious. Composer themselves recommend omitting the 'version' from the package composer.json (https://getcomposer.org/doc/04-schema.md#version). The reason for this is many-fold, however from a code maintenance point of view not having to bump the version in multiple places on every commit is key. In short, rejigging everything (including releases made in GitHub) because you forgot to bump all the versions in a commit is a pain. Having the version defined in the composer.json on the repository can also restrict the flexibility of installing the package via Composer and Packagist when installing using aliases etc.

At the point of uploading versions of the module to the Magento marketplace I would prescribe making the quick relevant changes to the package before uploading it. So on each tagged release in GitHub (which won't be that often), download the zip, add the version to composer.json and update the PSR-4 to reflect a move of the code to the folder root.

I hope this makes sense? Of course happy to discuss options here as necessary.
